//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inSSIDer.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("inSSIDer.Localization.LocalizerResources", typeof(LocalizerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude {0}.
        /// </summary>
        internal static string AltitudePlusValue {
            get {
                return ResourceManager.GetString("AltitudePlusValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amplitude [dB].
        /// </summary>
        internal static string AmplitudedBm {
            get {
                return ResourceManager.GetString("AmplitudedBm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is up to date.
        /// </summary>
        internal static string ApplicationUpToDate {
            get {
                return ResourceManager.GetString("ApplicationUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The .NET Framework configuration on this computer is corrputed, inSSIDer cannot continue. Repair the configuration and then run inSSIDer again.\r\n\r\nWe&apos;re sorry for any inconvenience..
        /// </summary>
        internal static string ConfigSystemError {
            get {
                return ResourceManager.GetString("ConfigSystemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ** Please provide a brief description of what was happening immediately prior to this error **.
        /// </summary>
        internal static string ErrorDescription {
            get {
                return ResourceManager.GetString("ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you trying to export to Program Files?
        ///Try exporting to another directory..
        /// </summary>
        internal static string ErrorExportDirectory {
            get {
                return ResourceManager.GetString("ErrorExportDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a directory to place the output KML files..
        /// </summary>
        internal static string ErrorKmlDirectoryMissing {
            get {
                return ResourceManager.GetString("ErrorKmlDirectoryMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least 1 GPX log to convert..
        /// </summary>
        internal static string ErrorNoLogFileSelected {
            get {
                return ResourceManager.GetString("ErrorNoLogFileSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Complete.
        /// </summary>
        internal static string ExportComplete {
            get {
                return ResourceManager.GetString("ExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Exists.
        /// </summary>
        internal static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix Type: {0}.
        /// </summary>
        internal static string FixTypePlusValue {
            get {
                return ResourceManager.GetString("FixTypePlusValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS: Fix Lost.
        /// </summary>
        internal static string GPSFixLost {
            get {
                return ResourceManager.GetString("GPSFixLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS: Off.
        /// </summary>
        internal static string GPSOff {
            get {
                return ResourceManager.GetString("GPSOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS: On.
        /// </summary>
        internal static string GPSOn {
            get {
                return ResourceManager.GetString("GPSOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening one of the selected log files. Make sure inSSIDer is not still logging to it..
        /// </summary>
        internal static string GpxFileOpenError {
            get {
                return ResourceManager.GetString("GpxFileOpenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDOP: {0}.
        /// </summary>
        internal static string HDOPPlusValue {
            get {
                return ResourceManager.GetString("HDOPPlusValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error attempting to use interface.
        ///
        ///Make sure you have selected a WiFi adapter, not an Ethernet adapter..
        /// </summary>
        internal static string InterfaceError {
            get {
                return ResourceManager.GetString("InterfaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude: {0}.
        /// </summary>
        internal static string LatitudePlusValue {
            get {
                return ResourceManager.GetString("LatitudePlusValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging: Off.
        /// </summary>
        internal static string LoggingOff {
            get {
                return ResourceManager.GetString("LoggingOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging to.
        /// </summary>
        internal static string LoggingTo {
            get {
                return ResourceManager.GetString("LoggingTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude {0}.
        /// </summary>
        internal static string LongitudePlusValue {
            get {
                return ResourceManager.GetString("LongitudePlusValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Wi-Fi interfaces found!.
        /// </summary>
        internal static string NoWiFiInterfacesFound {
            get {
                return ResourceManager.GetString("NoWiFiInterfacesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Wireless Interface.
        /// </summary>
        internal static string NoWirelessInterface {
            get {
                return ResourceManager.GetString("NoWirelessInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDOP: {0}.
        /// </summary>
        internal static string PDOPPlusValue {
            get {
                return ResourceManager.GetString("PDOPPlusValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satellites (U/V): {0} / {1}.
        /// </summary>
        internal static string SatellitesUVPlusValue {
            get {
                return ResourceManager.GetString("SatellitesUVPlusValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed (km/h): {0}.
        /// </summary>
        internal static string SpeedPlusValue {
            get {
                return ResourceManager.GetString("SpeedPlusValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Logging.
        /// </summary>
        internal static string StartLogging {
            get {
                return ResourceManager.GetString("StartLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Logging.
        /// </summary>
        internal static string StopLogging {
            get {
                return ResourceManager.GetString("StopLogging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn GPS Off.
        /// </summary>
        internal static string TurnGPSOff {
            get {
                return ResourceManager.GetString("TurnGPSOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn GPS On.
        /// </summary>
        internal static string TurnGPSOn {
            get {
                return ResourceManager.GetString("TurnGPSOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VDOP: {0}.
        /// </summary>
        internal static string VDOPPlusValue {
            get {
                return ResourceManager.GetString("VDOPPlusValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for data.
        /// </summary>
        internal static string WaitingForData {
            get {
                return ResourceManager.GetString("WaitingForData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;Comprehensive.kml&quot; already exists in the output folder. Overwrite?.
        /// </summary>
        internal static string WarningComprehensiveKmlExists {
            get {
                return ResourceManager.GetString("WarningComprehensiveKmlExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;Summary.kml&quot; already exists in the output folder. Overwrite?.
        /// </summary>
        internal static string WarningSummaryKmlExists {
            get {
                return ResourceManager.GetString("WarningSummaryKmlExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: wlanapi.dll could not be found..
        /// </summary>
        internal static string WlanapiNotFound {
            get {
                return ResourceManager.GetString("WlanapiNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inSSIDer requires the WLAN AutoConfig service, which appears to be stopped. 
        ///Please start WLAN AutoConfig and then run inSSIDer. 
        ///
        ///Thanks!.
        /// </summary>
        internal static string WlanServiceNotFound7 {
            get {
                return ResourceManager.GetString("WlanServiceNotFound7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inSSIDer requires the Wireless Zero Configuration (WZC) Service, which appears to be stopped. 
        ///Please start WZC and then run inSSIDer. 
        ///
        ///Thanks!.
        /// </summary>
        internal static string WlanServiceNotFoundXP {
            get {
                return ResourceManager.GetString("WlanServiceNotFoundXP", resourceCulture);
            }
        }
    }
}
