// Assembly ManagedWifi, Version 2010.6.21.0
[assembly: System.Reflection.AssemblyVersion("2010.10.27.0")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Reflection.AssemblyTitle("Managed Wifi API")]
[assembly: System.Reflection.AssemblyDescription(".NET managed wrapper for Windows Native Wifi API.")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyCompany("Monfort Software Engineering")]
[assembly: System.Reflection.AssemblyProduct("Managed Wifi API")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Monfort Software Engineering 2007")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.InteropServices.Guid("e7646a9f-2d07-455a-b9ae-51eaf7281d2f")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.11.1027")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]